#!/usr/bin/env python3
"""Generate docs/MCP_TOOLS.md from the live MCP server's tool registry, so the
tool reference never drifts from the actual @mcp.tool() definitions.

Run: uv run --directory <project> python scripts/generate_mcp_docs.py
`--check` writes nothing and exits non-zero if the file is stale -- the form
tests/test_scripts.py uses, mirroring scripts/generate_commands.py's --check.
This file went undetected as stale for a full domain-removal commit before
that check existed (2026-10-07) -- it's the reason the check exists now.
"""
from __future__ import annotations

import asyncio
import os
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT / "src"))

from fastmcp import Client
from fastmcp.client.transports import StdioTransport


async def build() -> str:
    env = dict(os.environ)
    # The repo's .env defaults to streamable-http; docs generation needs stdio.
    env["MCP_TRANSPORT"] = "stdio"
    transport = StdioTransport(
        command="uv", args=["run", "--directory", str(ROOT), "python", "src/minimax_mcp/server.py"],
        cwd=str(ROOT), env=env,
    )
    async with Client(transport) as client:
        tools = await client.list_tools()

    lines = [
        "<!-- AUTO-GENERATED by scripts/generate_mcp_docs.py — do not edit by hand -->",
        "# MCP Tools Reference",
        "",
        f"{len(tools)} tools exposed by `src/minimax_mcp/server.py`.",
        "",
    ]
    for tool in sorted(tools, key=lambda t: t.name):
        lines.append(f"## `{tool.name}`")
        lines.append("")
        lines.append(tool.description or "_(no description)_")
        lines.append("")
        props = (tool.inputSchema or {}).get("properties", {})
        required = set((tool.inputSchema or {}).get("required", []))
        if props:
            lines.append("| Parameter | Type | Required | Description |")
            lines.append("|---|---|---|---|")
            for name, schema in props.items():
                ptype = schema.get("type", "any")
                desc = schema.get("description", "")
                lines.append(f"| `{name}` | {ptype} | {'yes' if name in required else 'no'} | {desc} |")
            lines.append("")

    return "\n".join(lines)


async def main() -> None:
    content = await build()
    out_path = ROOT / "docs" / "MCP_TOOLS.md"

    if "--check" in sys.argv:
        current = out_path.read_text(encoding="utf-8") if out_path.exists() else None
        if current != content:
            print(f"{out_path} is stale -- run without --check to regenerate")
            sys.exit(1)
        print(f"{out_path} is up to date")
        return

    out_path.write_text(content, encoding="utf-8")
    print(f"Wrote {out_path}")


if __name__ == "__main__":
    asyncio.run(main())
